### ISSUE TITLE
Fails on sklearn 0.17

### ISSUE THREAD

**Issue by nwbvt** [ajtulloch/sklearn-compiledtrees#6]
I'm running into issues trying to use this with sklearn 0.17.  The error I'm getting is 
```
import compiledtrees
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbrown/.virtualenvs/castle/lib/python2.7/site-packages/compiledtrees/__init__.py", line 1, in <module>
    from compiledtrees.compiled import CompiledRegressionPredictor
  File "/Users/nbrown/.virtualenvs/castle/lib/python2.7/site-packages/compiledtrees/compiled.py", line 3, in <module>
    from sklearn.utils import array2d
ImportError: cannot import name array2d
```
It looks like the import of array2d into sklearn.utils was removed in 0.16.

**Comment by nwbvt** [comment]
Actually this may just be an issue with the version on PyPi which I guess is a bit old, the one on master seems to work.
